name: Fly Deploy
on:
  push:
    branches:
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Insert gh packages token
        run: echo "//npm.pkg.github.com/:_authToken=${{secrets.NODE_AUTH_TOKEN}}" >> .npmrc
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions@1.5
        with:
          args: "deploy --build-arg NODE_AUTH_TOKEN=${{secrets.NODE_AUTH_TOKEN}}"
